version: "3.9"

networks:
  chicofood-network:
    driver: bridge

services:
  chicofood-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    networks:
      - chicofood-network

  chicofood-redis:
    image: redis:6.2.1-alpine
    networks:
      - chicofood-network

  chicofood-api:
    image: chicofood-api
    command: ["/wait-for-it.sh", "chicofood-mysql:3306", "-t",  "30",  "--", "java", "-jar", "api.jar"]
    environment:
      DB_HOST: chicofood-mysql
      SPRING_SESSION_STORE_TYPE: redis
      SPRING_REDIS_HOST: chicofood-redis
    networks:
      - chicofood-network
    depends_on:
      - chicofood-mysql

  chicofood-proxy:
    build: ./ngnix
    image: chicofood-proxy
    ports:
      - "80:80"
    networks:
      - chicofood-network
    depends_on:
      - chicofood-api